export const NIFTY50 = [
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'INFY.NS', name: 'Infosys', sector: 'IT' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', sector: 'Banking' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'ITC.NS', name: 'ITC Limited', sector: 'FMCG' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank', sector: 'Banking' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro', sector: 'Construction' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints', sector: 'Paints' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki', sector: 'Auto' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance', sector: 'Finance' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical', sector: 'Pharma' },
  { symbol: 'TITAN.NS', name: 'Titan Company', sector: 'Consumer' },
  { symbol: 'WIPRO.NS', name: 'Wipro', sector: 'IT' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv', sector: 'Finance' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'NESTLEIND.NS', name: 'Nestlé India', sector: 'FMCG' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corp', sector: 'Utilities' },
  { symbol: 'NTPC.NS', name: 'NTPC Limited', sector: 'Energy' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra', sector: 'Auto' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel', sector: 'Metals' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance', sector: 'Insurance' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance', sector: 'Insurance' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries', sector: 'Diversified' },
  { symbol: 'BPCL.NS', name: 'BPCL', sector: 'Energy' },
  { symbol: 'DIVISLAB.NS', name: 'Divis Laboratories', sector: 'Pharma' },
  { symbol: 'CIPLA.NS', name: 'Cipla', sector: 'Pharma' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'ONGC.NS', name: 'ONGC', sector: 'Energy' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products', sector: 'FMCG' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', sector: 'Auto' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'DRREDDY.NS', name: 'Dr. Reddy\'s Labs', sector: 'Pharma' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports', sector: 'Infrastructure' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel', sector: 'Metals' },
  { symbol: 'COALINDIA.NS', name: 'Coal India', sector: 'Mining' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries', sector: 'FMCG' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries', sector: 'Metals' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'UPL.NS', name: 'UPL Limited', sector: 'Agrochemicals' },
  { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance', sector: 'Finance' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto', sector: 'Auto' },
  { symbol: 'TRENT.NS', name: 'Trent Limited', sector: 'Retail' },
]

export const TOP_CRYPTO = [
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin' },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum' },
  { id: 'binancecoin', symbol: 'BNB', name: 'BNB' },
  { id: 'ripple', symbol: 'XRP', name: 'XRP' },
  { id: 'solana', symbol: 'SOL', name: 'Solana' },
  { id: 'dogecoin', symbol: 'DOGE', name: 'Dogecoin' },
  { id: 'cardano', symbol: 'ADA', name: 'Cardano' },
  { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche' },
  { id: 'polkadot', symbol: 'DOT', name: 'Polkadot' },
  { id: 'tron', symbol: 'TRX', name: 'TRON' },
  { id: 'shiba-inu', symbol: 'SHIB', name: 'Shiba Inu' },
  { id: 'chainlink', symbol: 'LINK', name: 'Chainlink' },
  { id: 'litecoin', symbol: 'LTC', name: 'Litecoin' },
  { id: 'near', symbol: 'NEAR', name: 'NEAR Protocol' },
  { id: 'uniswap', symbol: 'UNI', name: 'Uniswap' },
  { id: 'internet-computer', symbol: 'ICP', name: 'Internet Computer' },
  { id: 'cosmos', symbol: 'ATOM', name: 'Cosmos' },
  { id: 'monero', symbol: 'XMR', name: 'Monero' },
  { id: 'stellar', symbol: 'XLM', name: 'Stellar' },
  { id: 'okb', symbol: 'OKB', name: 'OKB' },
]

export const TIMEFRAMES = [
  { label: '1m', value: '1m', yf: '1m', range: '7d' },
  { label: '5m', value: '5m', yf: '5m', range: '60d' },
  { label: '15m', value: '15m', yf: '15m', range: '60d' },
  { label: '1H', value: '60m', yf: '60m', range: '730d' },
  { label: '4H', value: '4h', yf: '60m', range: '730d' },
  { label: '1D', value: '1d', yf: '1d', range: '5y' },
  { label: '1W', value: '1wk', yf: '1wk', range: 'max' },
]

export const INDICATOR_TYPES = [
  { type: 'EMA', label: 'EMA', description: 'Exponential Moving Average', params: [{ name: 'period', label: 'Period', default: 20 }] },
  { type: 'SMA', label: 'SMA', description: 'Simple Moving Average', params: [{ name: 'period', label: 'Period', default: 20 }] },
  { type: 'RSI', label: 'RSI', description: 'Relative Strength Index', params: [{ name: 'period', label: 'Period', default: 14 }] },
  { type: 'MACD', label: 'MACD', description: 'MACD', params: [
    { name: 'fast', label: 'Fast Period', default: 12 },
    { name: 'slow', label: 'Slow Period', default: 26 },
    { name: 'signal', label: 'Signal Period', default: 9 },
  ]},
  { type: 'BB', label: 'Bollinger Bands', description: 'Bollinger Bands', params: [
    { name: 'period', label: 'Period', default: 20 },
    { name: 'stdDev', label: 'Std Dev', default: 2 },
  ]},
  { type: 'ATR', label: 'ATR', description: 'Average True Range', params: [{ name: 'period', label: 'Period', default: 14 }] },
  { type: 'VWAP', label: 'VWAP', description: 'Volume Weighted Average Price', params: [] },
]

export const CONDITION_TYPES = [
  { type: 'crossover', label: 'Crosses Above', requiresTwo: true },
  { type: 'crossunder', label: 'Crosses Below', requiresTwo: true },
  { type: 'above', label: 'Is Above', requiresTwo: true },
  { type: 'below', label: 'Is Below', requiresTwo: true },
  { type: 'above_value', label: 'Is Above Value', requiresTwo: false, requiresValue: true },
  { type: 'below_value', label: 'Is Below Value', requiresTwo: false, requiresValue: true },
]

export const STOP_LOSS_TYPES = [
  { type: 'last_candle_low', label: 'Low of Last Candle' },
  { type: 'atr_multiplier', label: 'ATR Multiplier', hasValue: true, valuePlaceholder: 'Multiplier (e.g. 2.0)' },
  { type: 'fixed_percent', label: 'Fixed Percentage', hasValue: true, valuePlaceholder: '% below entry' },
  { type: 'trailing', label: 'Trailing Stop %', hasValue: true, valuePlaceholder: 'Trail % (e.g. 2.0)' },
  { type: 'none', label: 'None' },
]

export const TAKE_PROFIT_TYPES = [
  { type: 'risk_reward', label: 'Risk:Reward Ratio', hasValue: true, valuePlaceholder: 'Ratio (e.g. 2.0)' },
  { type: 'fixed_percent', label: 'Fixed Percentage', hasValue: true, valuePlaceholder: '% above entry' },
  { type: 'none', label: 'None' },
]

export const INFO_EXPLANATIONS = {
  ema: {
    title: 'EMA — Exponential Moving Average',
    simple: 'An EMA is a running average that gives more weight to recent prices. It reacts faster to price changes than a regular average.',
    analogy: 'Think of it like asking 9 people about a stock — but you trust the most recent person\'s opinion 5× more than the oldest one.',
    formula: 'EMA = Price × k + Previous EMA × (1 − k)   where k = 2/(n+1)',
    svg: 'ema',
  },
  sma: {
    title: 'SMA — Simple Moving Average',
    simple: 'An SMA is the plain average of the last N closing prices. Every price gets equal weight.',
    analogy: 'Like averaging your last 20 exam scores — all scores count equally.',
    svg: 'sma',
  },
  rsi: {
    title: 'RSI — Relative Strength Index',
    simple: 'RSI is a 0–100 score showing how overbought or oversold a stock is. Above 70 = likely overbought (may fall). Below 30 = likely oversold (may rise).',
    analogy: 'Like a "hype meter" — when everyone\'s too excited (>70), a pullback is due. When everyone\'s panicking (<30), it might bounce.',
    svg: 'rsi',
  },
  macd: {
    title: 'MACD — Moving Average Convergence Divergence',
    simple: 'MACD measures momentum by comparing two EMAs. When the MACD line crosses above the signal line → bullish momentum.',
    analogy: 'It\'s like a speedometer for price movement. Crossing above zero = accelerating upward.',
    svg: 'macd',
  },
  bb: {
    title: 'Bollinger Bands',
    simple: 'Three lines: a middle SMA, and upper/lower bands 2 standard deviations away. Price bouncing off the lower band = potential buy.',
    analogy: 'Like boundaries on a highway — when price touches the edge, it usually bounces back toward the center.',
    svg: 'bb',
  },
  backtesting: {
    title: 'Backtesting',
    simple: 'Running your trading strategy on historical data to see how it would have performed in the past. It\'s a simulation — not a guarantee of future results.',
    analogy: 'Like using old football game footage to test if your new play strategy would have won.',
    svg: 'backtest',
  },
  sharpe: {
    title: 'Sharpe Ratio',
    simple: 'Measures return per unit of risk. Higher is better. Above 1.0 = good, above 2.0 = excellent. Below 0 = the strategy lost you money vs. risk-free investing.',
    analogy: 'If two drivers drove 100km — one smoothly, one swerving — the smooth one has a better Sharpe.',
    svg: 'sharpe',
  },
  drawdown: {
    title: 'Max Drawdown',
    simple: 'The largest peak-to-trough decline in your portfolio. If you had ₹1,00,000 and it fell to ₹70,000 before recovering, your max drawdown is 30%.',
    analogy: 'The worst dip you had to "stomach" during the strategy\'s run.',
    svg: 'drawdown',
  },
  profitfactor: {
    title: 'Profit Factor',
    simple: 'Total profit from winning trades ÷ Total loss from losing trades. Above 1.5 = good. Above 2.0 = excellent.',
    analogy: 'If you earned ₹2 for every ₹1 you lost, your profit factor is 2.0.',
    svg: 'profit',
  },
  crossover: {
    title: 'Crossover Signal',
    simple: 'A crossover happens when a faster line (e.g. EMA9) rises above a slower line (EMA20). This signals upward momentum — a potential buy.',
    analogy: 'Like a fast runner overtaking a slow runner — the faster one is gaining strength.',
    svg: 'crossover',
  },
  stoploss: {
    title: 'Stop Loss',
    simple: 'An automatic exit order that closes your position if the price falls below a set level — to limit losses.',
    analogy: 'Like a safety net in a circus. You hope you never use it, but it\'s there to protect you from a catastrophic fall.',
    svg: 'stoploss',
  },
  winrate: {
    title: 'Win Rate',
    simple: 'The percentage of trades that were profitable. 60% win rate = 6 out of 10 trades were winners.',
    analogy: 'A cricket batsman with a 60% boundary rate vs a 40% one — the higher, the better (though it\'s not the whole picture).',
    svg: 'winrate',
  },
}

export const DEFAULT_STRATEGY = {
  name: 'EMA 9/20 Crossover',
  description: 'Classic trend-following strategy using EMA crossovers',
  market: 'indian',
  indicators: [
    { id: 'ema9', type: 'EMA', period: 9, source: 'close', color: '#00E5A0' },
    { id: 'ema20', type: 'EMA', period: 20, source: 'close', color: '#FFB800' },
  ],
  conditions: {
    longEntry: [{ type: 'crossover', a: 'ema9', b: 'ema20' }],
    longExit: [{ type: 'crossunder', a: 'ema9', b: 'ema20' }],
    shortEntry: [{ type: 'crossunder', a: 'ema9', b: 'ema20' }],
    shortExit: [{ type: 'crossover', a: 'ema9', b: 'ema20' }],
  },
  stopLoss: { type: 'last_candle_low', value: null },
  takeProfit: { type: 'none', value: null },
  tradeDirection: 'both',
  capital: 100000,
  positionSize: 10,
}
